#!/bin/sh

set -e

echo "Just-built file called, args: $@" >&2

export LD_LIBRARY_PATH="$CURDIR/debian/tmp/usr/lib/$DEB_HOST_MULTIARCH"
exec "$CURDIR/debian/tmp/usr/bin/file" \
    -m "$CURDIR/debian/tmp/usr/share/file/magic.mgc" \
    "$@"
